//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此原始程式碼由 wsdl 版本=4.6.1055.0 自動產生。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="AgvWebServiceSoap", Namespace="http://tempuri.org/")]
public partial class AgvWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback EquRunningOperationCompleted;
    
    private System.Threading.SendOrPostCallback DeliverTimeOperationCompleted;
    
    private System.Threading.SendOrPostCallback EquPurchaseStatusOperationCompleted;
    
    private System.Threading.SendOrPostCallback EquUtlizationOperationCompleted;
    
    /// <remarks/>
    public AgvWebService() {
        this.Url = "http://localhost:51725/AgvWebService.asmx";
    }
    
    /// <remarks/>
    public event EquRunningCompletedEventHandler EquRunningCompleted;
    
    /// <remarks/>
    public event DeliverTimeCompletedEventHandler DeliverTimeCompleted;
    
    /// <remarks/>
    public event EquPurchaseStatusCompletedEventHandler EquPurchaseStatusCompleted;
    
    /// <remarks/>
    public event EquUtlizationCompletedEventHandler EquUtlizationCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EquRunning", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool EquRunning(string equName, double data_value, System.DateTime record_time) {
        object[] results = this.Invoke("EquRunning", new object[] {
                    equName,
                    data_value,
                    record_time});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginEquRunning(string equName, double data_value, System.DateTime record_time, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("EquRunning", new object[] {
                    equName,
                    data_value,
                    record_time}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndEquRunning(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void EquRunningAsync(string equName, double data_value, System.DateTime record_time) {
        this.EquRunningAsync(equName, data_value, record_time, null);
    }
    
    /// <remarks/>
    public void EquRunningAsync(string equName, double data_value, System.DateTime record_time, object userState) {
        if ((this.EquRunningOperationCompleted == null)) {
            this.EquRunningOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEquRunningOperationCompleted);
        }
        this.InvokeAsync("EquRunning", new object[] {
                    equName,
                    data_value,
                    record_time}, this.EquRunningOperationCompleted, userState);
    }
    
    private void OnEquRunningOperationCompleted(object arg) {
        if ((this.EquRunningCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.EquRunningCompleted(this, new EquRunningCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeliverTime", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool DeliverTime(string equName, int data_value, System.DateTime record_time) {
        object[] results = this.Invoke("DeliverTime", new object[] {
                    equName,
                    data_value,
                    record_time});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDeliverTime(string equName, int data_value, System.DateTime record_time, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DeliverTime", new object[] {
                    equName,
                    data_value,
                    record_time}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndDeliverTime(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void DeliverTimeAsync(string equName, int data_value, System.DateTime record_time) {
        this.DeliverTimeAsync(equName, data_value, record_time, null);
    }
    
    /// <remarks/>
    public void DeliverTimeAsync(string equName, int data_value, System.DateTime record_time, object userState) {
        if ((this.DeliverTimeOperationCompleted == null)) {
            this.DeliverTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeliverTimeOperationCompleted);
        }
        this.InvokeAsync("DeliverTime", new object[] {
                    equName,
                    data_value,
                    record_time}, this.DeliverTimeOperationCompleted, userState);
    }
    
    private void OnDeliverTimeOperationCompleted(object arg) {
        if ((this.DeliverTimeCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DeliverTimeCompleted(this, new DeliverTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EquPurchaseStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool EquPurchaseStatus(string equName, int data_value, System.DateTime record_time) {
        object[] results = this.Invoke("EquPurchaseStatus", new object[] {
                    equName,
                    data_value,
                    record_time});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginEquPurchaseStatus(string equName, int data_value, System.DateTime record_time, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("EquPurchaseStatus", new object[] {
                    equName,
                    data_value,
                    record_time}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndEquPurchaseStatus(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void EquPurchaseStatusAsync(string equName, int data_value, System.DateTime record_time) {
        this.EquPurchaseStatusAsync(equName, data_value, record_time, null);
    }
    
    /// <remarks/>
    public void EquPurchaseStatusAsync(string equName, int data_value, System.DateTime record_time, object userState) {
        if ((this.EquPurchaseStatusOperationCompleted == null)) {
            this.EquPurchaseStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEquPurchaseStatusOperationCompleted);
        }
        this.InvokeAsync("EquPurchaseStatus", new object[] {
                    equName,
                    data_value,
                    record_time}, this.EquPurchaseStatusOperationCompleted, userState);
    }
    
    private void OnEquPurchaseStatusOperationCompleted(object arg) {
        if ((this.EquPurchaseStatusCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.EquPurchaseStatusCompleted(this, new EquPurchaseStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EquUtlization", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public bool EquUtlization(string equName, int data_value, System.DateTime record_time) {
        object[] results = this.Invoke("EquUtlization", new object[] {
                    equName,
                    data_value,
                    record_time});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginEquUtlization(string equName, int data_value, System.DateTime record_time, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("EquUtlization", new object[] {
                    equName,
                    data_value,
                    record_time}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndEquUtlization(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void EquUtlizationAsync(string equName, int data_value, System.DateTime record_time) {
        this.EquUtlizationAsync(equName, data_value, record_time, null);
    }
    
    /// <remarks/>
    public void EquUtlizationAsync(string equName, int data_value, System.DateTime record_time, object userState) {
        if ((this.EquUtlizationOperationCompleted == null)) {
            this.EquUtlizationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEquUtlizationOperationCompleted);
        }
        this.InvokeAsync("EquUtlization", new object[] {
                    equName,
                    data_value,
                    record_time}, this.EquUtlizationOperationCompleted, userState);
    }
    
    private void OnEquUtlizationOperationCompleted(object arg) {
        if ((this.EquUtlizationCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.EquUtlizationCompleted(this, new EquUtlizationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void EquRunningCompletedEventHandler(object sender, EquRunningCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class EquRunningCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal EquRunningCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void DeliverTimeCompletedEventHandler(object sender, DeliverTimeCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DeliverTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DeliverTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void EquPurchaseStatusCompletedEventHandler(object sender, EquPurchaseStatusCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class EquPurchaseStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal EquPurchaseStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void EquUtlizationCompletedEventHandler(object sender, EquUtlizationCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class EquUtlizationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal EquUtlizationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}
